// eslint-disable-next-line import/no-anonymous-default-export
export default {
    name: "Amir Mohammad Rahimi",
    home: 'HOME',
    about: 'ABOUT',
    resume: 'RESUME',
    portfolios: 'PORTFOLIOS',
    contact: 'CONTACT',
    hi: 'Hi, I am ',
    hi2: '',
    desc: 'i am a React.js and Java EE developer. I am interested in front-end programming',
    aboutMe: 'ABOUT ME',
    services: 'SERVICES',
    fullName: 'Full Name',
    age: 'Age',
    nationality: 'Nationality',
    languages: 'Languages',
    phone: 'Phone',
    years: 'Years',
    iranian: 'Iranian',
    persian: 'Persian',
    english: 'English',
    mobileNumber: '(+98)9393347982',
    downloadCv: 'download cv',
    AIDevelopment: 'AI Development',
    AIDevelopmentDesc: 'Experience implementing a variety of machine learning and deep learning models and working with a variety of neural networks in various fields. Ability to accurately predict time series.',
    webDevelopment: 'Web Development',
    webDevelopmentDesc: 'I can develope a website Front-end using React js, javascrip, html and css. Also i,m available in using primefaces components for developing a website Front-end when the Back-end is implementaed in Java EE.',
    mobileApplication: 'Android Application',
    mobileApplicationDesc: 'Implementing various types of Android applications according to the latest methods in the world and using material design and material motion, as well as creating up-to-date and user-friendly designs.',
    mySkills: 'MY SKILLS',
    workingSteps: [
        { id: -1, date: "", title: "", subtitle: "", content: "" },
        { id: 0, date: "2020-2021", title: "Java Expert", subtitle: "Behpardaz Jahan", content: "In this company, I was engaged in Java EE programming, Android and site design." },
        { id: -2, date: "", title: "", subtitle: "", content: "" },
    ],
    educationalSteps: [
        { id: -1, date: "", title: "", subtitle: "", content: "" },
        { id: 0, date: "2021-2023", title: "Master of Science", subtitle: "Malek Ashtar University of Technology", content: "Avg. 17.70" },
        { id: 1, date: "2017-2021", title: "Bachelor of Science", subtitle: "Payam Nour University", content: "Avg. 16.46" },
        { id: 2, date: "2013-2017", title: "High School Garduation", subtitle: "Dehkhoda High School", content: "Avg. 17.32" },
        { id: -2, date: "", title: "", subtitle: "", content: "" },
    ],
    workingExperience: 'Working Experience',
    educationalQualification: 'Educational Qualification',
    contanctMe: 'CONTACT ME',
    getInTouch: 'Get In Touch',
    enterYourName: 'Enter Your Name',
    enterYourEmail: 'Enter Your Email',
    enterYourSubject: 'Enter Your Subject',
    enterYourMessag: 'Enter Your Message',
    sendMessage: 'Send Message',
    email: 'Email',
    address: 'Address',
    mobile1: '+98-939 334 7982',
    mobile2: '+98-935 8 207 405',
    addressDetails: 'Iran, Alborz, Karaj, Baraghan Street, Emam Sajjad Street, 209 Yazdani Alley',
    portfoliosList: [
        { id: 2, title: 'Shoes Shopping', desc: 'Shoes Shopping website (React JS)', image: 'https://cdn-icons-png.flaticon.com/512/2742/2742830.png' },
        { id: 3, title: 'Mikhak System', desc: 'Integrated Consular Services Management System', image: 'https://www.hamrahmoshaver.com/upload/articles/big/1884025465%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%85%DB%8C%D8%AE%DA%A9.jpg' },
        { id: 4, title: 'LIMA', desc: 'Memorable moments of Iranian music', image: 'https://avayefarda.com/wp-content/uploads/2020/09/photo_2020-09-14_20-36-33.jpg' },
        { id: 5, title: 'Hesse Zibayi', desc: 'Social network for face and hair makeup and a variety of attractive makeup tips', image: 'https://s.cafebazaar.ir/images/upload/screenshot/com.hamed_heydari.hesseZibayi-844752326641.jpg?x-img=v1/resize,h_800/format,type_webp,lossless_false' },
        { id: 6, title: 'Billboard', desc: 'A platform for free publication of all kinds of advertisements and the need to buy and sell new and used goods', image: 'https://www.pngplay.com/wp-content/uploads/6/Billboard-Icon-PNG-Clipart-Background.png' },
    ]
}